### ISSUE TITLE
Notes area not filling available container height

### ISSUE THREAD

**Issue by Hahlh** [mrkolby/sanity-plugin-dashboard-widget-notes#7]
Good day, I hope you are doing great!

Thank you for developing this. It's nice to see such a useful dashboard plugin!

The title should already be plenty descriptive: 
![image](https://user-images.githubusercontent.com/45669613/114665511-6b8d1880-9cfd-11eb-909d-d733b27ade67.png)

Is this an issue with how I set the layout? You likely don't have that problem yourself as it would be quite obvious and you would have fixed it?

All the best!

**Comment by Hahlh** [comment]
`height: -moz-available` seems to override the `height: 100%` set in the stylesheet:
[https://github.com/mrkolby/sanity-plugin-dashboard-widget-notes/blob/3a1482bf501e572f6b9f91b05309e04872a29996/src/Notes.css#L54](https://github.com/mrkolby/sanity-plugin-dashboard-widget-notes/blob/3a1482bf501e572f6b9f91b05309e04872a29996/src/Notes.css#L54)
Firefox nevertheless seems to think, that this style comes from this sheet, although it isn't declared:
![image](https://user-images.githubusercontent.com/45669613/114668550-2c60c680-9d01-11eb-9050-2450e3fb09e6.png)


A quick, but dirty fix could be to add `!important` to the `height: 100%` declaration.
I will create a little PR for this and you decide, whether that is good enough :+1:

**Comment by byebyers** [comment]
Is there an update on this?

**Comment by byebyers** [comment]
Will this be published on NPM soon?

**Comment by mrkolby** [comment]
@byebyers Try now.

**Comment by byebyers** [comment]
Thank you so much @mrkolby !
